# This is a basic workflow to help you get started with Actions
name: CI
on: 
  push:
    paths-ignore:
      - '**/*.md'
jobs:
  Job-DotNet-Push:
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 3.1.x
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
      DOTNET_NOLOGO: true
      BUILD_CONFIGURATION: Release
      PROJECT_PATH: 'src/MyProject'
      PROJECT_TEST_PATH: 'tests/**.Tests'
    steps:
      - name: Check out repository code ('${{ github.repository }}' cloned to the runner)
        uses: actions/checkout@v2
    
      - name: Setup .NET Core SDK (${{ env.DOTNET_CORE_VERSION }})
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
 
      - name: Restore Packages
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build - .NET Core ${{ env.DOTNET_CORE_VERSION }}
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}
        working-directory: "${{ env.PROJECT_PATH }}"
        
      - name: Unit Tests 
        run: dotnet test ${{ env.PROJECT_TEST_PATH }}
